### ISSUE TITLE
Memory setting gets reset when enabled

### ISSUE THREAD

**Issue by shinji257** [feedthecraft/Launcher#1]
This probably shouldn't happen.  Ideally it would either preserve and re-use settings that are already keyed or disable the associated fields when not enabled.

I'll probably opt for the latter.

**Comment by Scavable** [comment]
The fields get disabled when the checkboxes are not selected but the data is still cleared. Still need to work on that.

**Comment by shinji257** [comment]
The clearing of data is currently expected behavior.  If you want to preserve data then you have to hunt down all the other checks for data and update them with the new method or relocate the old settings to temporary "settings" that can be referenced when the options are enabled.  I was just looking to prevent pre-emptive selection when the option wasn't on.
