### ISSUE TITLE
Java version not enforced

### ISSUE THREAD

**Issue by shinji257** [feedthecraft/Launcher#2]
The minimum java version needed to launch a particular version of Minecraft is stored in the instance json file for that pack.  We should check it against the version of Java we are trying to run for it and verify that it will meet that requirement.  If it doesn't then abort the whole process and present a message to the user in some form.  I'm thinking `LaunchSupervisor.java` is appropriate but it will need new imports and I don't know how to get the `getRuntime()` data in there.

So far I got this...
New imports
```java
import com.skcraft.launcher.launch.runtime.JavaRuntime;
import com.skcraft.launcher.model.minecraft.JavaVersion;
```

New variable (as part of first launch class)
```java
JavaVersion targetVersion;
```

Modified code (also part of same launch class)
```java
[snip]
                if (getRuntime().getMajorVersion() >= targetVersion.getMajorVersion()) {
                    // On success, launch also
                    Futures.addCallback(future, new FutureCallback<Instance>() {
                        @Override
                        public void onSuccess(Instance result) {
                            launch(window, instance, session, listener);
                        }

                        @Override
                        public void onFailure(Throwable t) {
                        }
                    }, SwingExecutor.INSTANCE);
                } else {
                    SwingHelper.showErrorDialog(window, "Error Min Version Message", "Error Min Version Dialog");
                }
            } else {
                if (getRuntime().getMajorVersion() >= targetVersion.getMajorVersion()) {
                    launch(window, instance, session, listener);
                } else {
                    SwingHelper.showErrorDialog(window, "Error Min Version Message", "Error Min Version Dialog");
                }
            }
        } catch (ArrayIndexOutOfBoundsException e) {
            SwingHelper.showErrorDialog(window, SharedLocale.tr("launcher.noInstanceError"), SharedLocale.tr("launcher.noInstanceTitle"));
        }
```

Error during build:
```
> Task :launcher:compileJava
P:\FeedTheCraft\skcraft\launcher\src\main\java\com\skcraft\launcher\launch\LaunchSupervisor.java:102: error: cannot find symbol
                if (getRuntime().getMajorVersion() >= targetVersion.getMajorVersion()) {
                    ^
  symbol:   method getRuntime()
  location: class LaunchSupervisor
P:\FeedTheCraft\skcraft\launcher\src\main\java\com\skcraft\launcher\launch\LaunchSupervisor.java:118: error: cannot find symbol
                if (getRuntime().getMajorVersion() >= targetVersion.getMajorVersion()) {
                    ^
  symbol:   method getRuntime()
  location: class LaunchSupervisor
2 errors
```

**Comment by Scavable** [comment]
Made it so only the java versions which meet the minimum will show in the instance settings custom java runtime. They may still be able to click add new jdk and choose a version below minimum but I have not tested that yet and will have a fix for it soon if that is the case.

**Comment by shinji257** [comment]
That's fine.  If they manually choose one that is below minimum then they should get a nice warning advising that the pack requires min X version and that they are using X version instead.  If they tell it to continue anyways then it is on them for doing so.  No need to block the manual selection.  Besides we might want to allow choosing it in the event the manifest is missing (for some reason) or it is wrong/unexpected.
